name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]
  # Test once a week
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test-github:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-22.04]
          julia-version: ['1.8']
          julia-arch: [x64]

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
